#! /bin/env bash
for monitor in $(bspc query -M); do
	bspc monitor -d • • • • • • • • • •
done

sxhkd 2> ~/.sxhkd.log &

bspc config border_width 5
bspc config window_gap 20

bspc config split_ratio 0.5
bspc config focus_follows_pointer true


feh --bg-scale ~/.bspwm/wallpaper.jpg

# Map caps lock to escape
setxkbmap -option "caps:escape"

# Hide cursor on typing
unclutter -idle 1 &
